format_version: 10
pipelines:
  jenkins-jobs:
    group: expense
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2ae7d73:
        git: https://github.com/pdevpos/learn-jenkins.git
        shallow_clone: false
        auto_update: true
        branch: main
        secure_variables:
          vault_token: "AES:9euutTDMWgSJcjgzn0dhGg==:RWq8EJGRQOCQ3N3k81IUBA=="
    stages:
      - DEV:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            vault-job:
              timeout: 0
              tasks:
                - exec: {command: ansible-playbook,arguments:["-i","172.31.34.117,","tools.yml","-e","tools_name=jenkins","-e","ansible_user=ec2-user","-e","ansible_password=DevOps321","-e","jenkins_job=true"],run_if: passed}

